# Generated by Django 3.0.1 on 2020-01-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=30)),
                ('point', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('order', models.IntegerField(default=0)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
