# Generated by Django 3.0.1 on 2020-01-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200101_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='band',
            name='order',
            field=models.IntegerField(default=0, verbose_name='順番'),
        ),
        migrations.AlterField(
            model_name='band',
            name='point',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='点数'),
        ),
    ]
