# Generated by Django 3.0.1 on 2020-01-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200101_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='band_name',
            field=models.CharField(max_length=30, verbose_name='バンド名'),
        ),
    ]
