# Generated by Django 3.0.1 on 2020-01-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200101_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['order', 'posted_date']},
        ),
    ]
