# Generated by Django 3.0.1 on 2020-01-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='count',
        ),
    ]
